import SearchBar from '../components/SearchBar';
import Accordion from '../components/Accordion';
import { useState } from 'react';
import GithubApi from '../utils/githubApi';

export default function App() {
  const [searchText, setSearchText] = useState('');

  return (
    <div>
      <div>
        <h1>React Community's <br/> Open Source Repo Directory</h1>
      </div>
      <div>
        <SearchBar 
          searchText={searchText}
          onSearchTextChange={setSearchText} />
      </div>
      <div>
        <Accordion
          repos={repos}
          searchText={searchText} />
      </div>
    </div>
  )
}

const repos = [{
  "id": 10270491,
  "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDQ5MQ==",
  "name": "react-bower",
  "full_name": "reactjs/react-bower",
  "private": false,
  "owner": {
      "login": "reactjs",
      "id": 6412038,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6412038?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reactjs",
      "html_url": "https://github.com/reactjs",
      "followers_url": "https://api.github.com/users/reactjs/followers",
      "following_url": "https://api.github.com/users/reactjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/reactjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reactjs/subscriptions",
      "organizations_url": "https://api.github.com/users/reactjs/orgs",
      "repos_url": "https://api.github.com/users/reactjs/repos",
      "events_url": "https://api.github.com/users/reactjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reactjs/received_events",
      "type": "Organization",
      "site_admin": false
  },
  "html_url": "https://github.com/reactjs/react-bower",
  "description": "[DISCONTINUED] Bower package for React",
  "fork": false,
  "url": "https://api.github.com/repos/reactjs/react-bower",
  "forks_url": "https://api.github.com/repos/reactjs/react-bower/forks",
  "keys_url": "https://api.github.com/repos/reactjs/react-bower/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/reactjs/react-bower/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/reactjs/react-bower/teams",
  "hooks_url": "https://api.github.com/repos/reactjs/react-bower/hooks",
  "issue_events_url": "https://api.github.com/repos/reactjs/react-bower/issues/events{/number}",
  "events_url": "https://api.github.com/repos/reactjs/react-bower/events",
  "assignees_url": "https://api.github.com/repos/reactjs/react-bower/assignees{/user}",
  "branches_url": "https://api.github.com/repos/reactjs/react-bower/branches{/branch}",
  "tags_url": "https://api.github.com/repos/reactjs/react-bower/tags",
  "blobs_url": "https://api.github.com/repos/reactjs/react-bower/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/reactjs/react-bower/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/reactjs/react-bower/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/reactjs/react-bower/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/reactjs/react-bower/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/reactjs/react-bower/languages",
  "stargazers_url": "https://api.github.com/repos/reactjs/react-bower/stargazers",
  "contributors_url": "https://api.github.com/repos/reactjs/react-bower/contributors",
  "subscribers_url": "https://api.github.com/repos/reactjs/react-bower/subscribers",
  "subscription_url": "https://api.github.com/repos/reactjs/react-bower/subscription",
  "commits_url": "https://api.github.com/repos/reactjs/react-bower/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/reactjs/react-bower/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/reactjs/react-bower/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/reactjs/react-bower/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/reactjs/react-bower/contents/{+path}",
  "compare_url": "https://api.github.com/repos/reactjs/react-bower/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/reactjs/react-bower/merges",
  "archive_url": "https://api.github.com/repos/reactjs/react-bower/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/reactjs/react-bower/downloads",
  "issues_url": "https://api.github.com/repos/reactjs/react-bower/issues{/number}",
  "pulls_url": "https://api.github.com/repos/reactjs/react-bower/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/reactjs/react-bower/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/reactjs/react-bower/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/reactjs/react-bower/labels{/name}",
  "releases_url": "https://api.github.com/repos/reactjs/react-bower/releases{/id}",
  "deployments_url": "https://api.github.com/repos/reactjs/react-bower/deployments",
  "created_at": "2013-05-24T16:29:15Z",
  "updated_at": "2024-02-10T16:32:02Z",
  "pushed_at": "2017-11-09T15:26:05Z",
  "git_url": "git://github.com/reactjs/react-bower.git",
  "ssh_url": "git@github.com:reactjs/react-bower.git",
  "clone_url": "https://github.com/reactjs/react-bower.git",
  "svn_url": "https://github.com/reactjs/react-bower",
  "homepage": "",
  "size": 6927,
  "stargazers_count": 69,
  "watchers_count": 69,
  "language": "JavaScript",
  "has_issues": false,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 45,
  "mirror_url": null,
  "archived": true,
  "disabled": false,
  "open_issues_count": 0,
  "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [],
  "visibility": "public",
  "forks": 45,
  "open_issues": 0,
  "watchers": 69,
  "default_branch": "master",
  "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
  }
},
{
  "id": 11667865,
  "node_id": "MDEwOlJlcG9zaXRvcnkxMTY2Nzg2NQ==",
  "name": "react-rails",
  "full_name": "reactjs/react-rails",
  "private": false,
  "owner": {
      "login": "reactjs",
      "id": 6412038,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6412038?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reactjs",
      "html_url": "https://github.com/reactjs",
      "followers_url": "https://api.github.com/users/reactjs/followers",
      "following_url": "https://api.github.com/users/reactjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/reactjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reactjs/subscriptions",
      "organizations_url": "https://api.github.com/users/reactjs/orgs",
      "repos_url": "https://api.github.com/users/reactjs/repos",
      "events_url": "https://api.github.com/users/reactjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reactjs/received_events",
      "type": "Organization",
      "site_admin": false
  },
  "html_url": "https://github.com/reactjs/react-rails",
  "description": "Integrate React.js with Rails views and controllers, the asset pipeline, or webpacker.",
  "fork": false,
  "url": "https://api.github.com/repos/reactjs/react-rails",
  "forks_url": "https://api.github.com/repos/reactjs/react-rails/forks",
  "keys_url": "https://api.github.com/repos/reactjs/react-rails/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/reactjs/react-rails/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/reactjs/react-rails/teams",
  "hooks_url": "https://api.github.com/repos/reactjs/react-rails/hooks",
  "issue_events_url": "https://api.github.com/repos/reactjs/react-rails/issues/events{/number}",
  "events_url": "https://api.github.com/repos/reactjs/react-rails/events",
  "assignees_url": "https://api.github.com/repos/reactjs/react-rails/assignees{/user}",
  "branches_url": "https://api.github.com/repos/reactjs/react-rails/branches{/branch}",
  "tags_url": "https://api.github.com/repos/reactjs/react-rails/tags",
  "blobs_url": "https://api.github.com/repos/reactjs/react-rails/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/reactjs/react-rails/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/reactjs/react-rails/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/reactjs/react-rails/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/reactjs/react-rails/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/reactjs/react-rails/languages",
  "stargazers_url": "https://api.github.com/repos/reactjs/react-rails/stargazers",
  "contributors_url": "https://api.github.com/repos/reactjs/react-rails/contributors",
  "subscribers_url": "https://api.github.com/repos/reactjs/react-rails/subscribers",
  "subscription_url": "https://api.github.com/repos/reactjs/react-rails/subscription",
  "commits_url": "https://api.github.com/repos/reactjs/react-rails/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/reactjs/react-rails/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/reactjs/react-rails/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/reactjs/react-rails/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/reactjs/react-rails/contents/{+path}",
  "compare_url": "https://api.github.com/repos/reactjs/react-rails/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/reactjs/react-rails/merges",
  "archive_url": "https://api.github.com/repos/reactjs/react-rails/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/reactjs/react-rails/downloads",
  "issues_url": "https://api.github.com/repos/reactjs/react-rails/issues{/number}",
  "pulls_url": "https://api.github.com/repos/reactjs/react-rails/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/reactjs/react-rails/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/reactjs/react-rails/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/reactjs/react-rails/labels{/name}",
  "releases_url": "https://api.github.com/repos/reactjs/react-rails/releases{/id}",
  "deployments_url": "https://api.github.com/repos/reactjs/react-rails/deployments",
  "created_at": "2013-07-25T18:27:18Z",
  "updated_at": "2024-06-26T09:04:26Z",
  "pushed_at": "2024-05-17T04:36:10Z",
  "git_url": "git://github.com/reactjs/react-rails.git",
  "ssh_url": "git@github.com:reactjs/react-rails.git",
  "clone_url": "https://github.com/reactjs/react-rails.git",
  "svn_url": "https://github.com/reactjs/react-rails",
  "homepage": "",
  "size": 8648,
  "stargazers_count": 6732,
  "watchers_count": 6732,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": false,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": true,
  "forks_count": 757,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 18,
  "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
      "jsx",
      "rails",
      "react",
      "react-rails",
      "ruby",
      "sprockets",
      "webpacker"
  ],
  "visibility": "public",
  "forks": 757,
  "open_issues": 18,
  "watchers": 6732,
  "default_branch": "master",
  "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
  }
},
{
  "id": 12601393,
  "node_id": "MDEwOlJlcG9zaXRvcnkxMjYwMTM5Mw==",
  "name": "react-art",
  "full_name": "reactjs/react-art",
  "private": false,
  "owner": {
      "login": "reactjs",
      "id": 6412038,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6412038?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reactjs",
      "html_url": "https://github.com/reactjs",
      "followers_url": "https://api.github.com/users/reactjs/followers",
      "following_url": "https://api.github.com/users/reactjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/reactjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reactjs/subscriptions",
      "organizations_url": "https://api.github.com/users/reactjs/orgs",
      "repos_url": "https://api.github.com/users/reactjs/repos",
      "events_url": "https://api.github.com/users/reactjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reactjs/received_events",
      "type": "Organization",
      "site_admin": false
  },
  "html_url": "https://github.com/reactjs/react-art",
  "description": "React Bridge to the ART Drawing Library",
  "fork": false,
  "url": "https://api.github.com/repos/reactjs/react-art",
  "forks_url": "https://api.github.com/repos/reactjs/react-art/forks",
  "keys_url": "https://api.github.com/repos/reactjs/react-art/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/reactjs/react-art/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/reactjs/react-art/teams",
  "hooks_url": "https://api.github.com/repos/reactjs/react-art/hooks",
  "issue_events_url": "https://api.github.com/repos/reactjs/react-art/issues/events{/number}",
  "events_url": "https://api.github.com/repos/reactjs/react-art/events",
  "assignees_url": "https://api.github.com/repos/reactjs/react-art/assignees{/user}",
  "branches_url": "https://api.github.com/repos/reactjs/react-art/branches{/branch}",
  "tags_url": "https://api.github.com/repos/reactjs/react-art/tags",
  "blobs_url": "https://api.github.com/repos/reactjs/react-art/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/reactjs/react-art/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/reactjs/react-art/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/reactjs/react-art/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/reactjs/react-art/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/reactjs/react-art/languages",
  "stargazers_url": "https://api.github.com/repos/reactjs/react-art/stargazers",
  "contributors_url": "https://api.github.com/repos/reactjs/react-art/contributors",
  "subscribers_url": "https://api.github.com/repos/reactjs/react-art/subscribers",
  "subscription_url": "https://api.github.com/repos/reactjs/react-art/subscription",
  "commits_url": "https://api.github.com/repos/reactjs/react-art/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/reactjs/react-art/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/reactjs/react-art/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/reactjs/react-art/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/reactjs/react-art/contents/{+path}",
  "compare_url": "https://api.github.com/repos/reactjs/react-art/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/reactjs/react-art/merges",
  "archive_url": "https://api.github.com/repos/reactjs/react-art/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/reactjs/react-art/downloads",
  "issues_url": "https://api.github.com/repos/reactjs/react-art/issues{/number}",
  "pulls_url": "https://api.github.com/repos/reactjs/react-art/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/reactjs/react-art/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/reactjs/react-art/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/reactjs/react-art/labels{/name}",
  "releases_url": "https://api.github.com/repos/reactjs/react-art/releases{/id}",
  "deployments_url": "https://api.github.com/repos/reactjs/react-art/deployments",
  "created_at": "2013-09-04T20:29:33Z",
  "updated_at": "2024-06-26T09:31:35Z",
  "pushed_at": "2019-05-20T12:18:29Z",
  "git_url": "git://github.com/reactjs/react-art.git",
  "ssh_url": "git@github.com:reactjs/react-art.git",
  "clone_url": "https://github.com/reactjs/react-art.git",
  "svn_url": "https://github.com/reactjs/react-art",
  "homepage": null,
  "size": 292,
  "stargazers_count": 1991,
  "watchers_count": 1991,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": true,
  "has_discussions": false,
  "forks_count": 177,
  "mirror_url": null,
  "archived": true,
  "disabled": false,
  "open_issues_count": 29,
  "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [],
  "visibility": "public",
  "forks": 177,
  "open_issues": 29,
  "watchers": 1991,
  "default_branch": "master",
  "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
  }
},
{
  "id": 15645447,
  "node_id": "MDEwOlJlcG9zaXRvcnkxNTY0NTQ0Nw==",
  "name": "react-magic",
  "full_name": "reactjs/react-magic",
  "private": false,
  "owner": {
      "login": "reactjs",
      "id": 6412038,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6412038?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reactjs",
      "html_url": "https://github.com/reactjs",
      "followers_url": "https://api.github.com/users/reactjs/followers",
      "following_url": "https://api.github.com/users/reactjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/reactjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reactjs/subscriptions",
      "organizations_url": "https://api.github.com/users/reactjs/orgs",
      "repos_url": "https://api.github.com/users/reactjs/repos",
      "events_url": "https://api.github.com/users/reactjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reactjs/received_events",
      "type": "Organization",
      "site_admin": false
  },
  "html_url": "https://github.com/reactjs/react-magic",
  "description": "Automatically AJAXify plain HTML with the power of React. It's magic!",
  "fork": false,
  "url": "https://api.github.com/repos/reactjs/react-magic",
  "forks_url": "https://api.github.com/repos/reactjs/react-magic/forks",
  "keys_url": "https://api.github.com/repos/reactjs/react-magic/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/reactjs/react-magic/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/reactjs/react-magic/teams",
  "hooks_url": "https://api.github.com/repos/reactjs/react-magic/hooks",
  "issue_events_url": "https://api.github.com/repos/reactjs/react-magic/issues/events{/number}",
  "events_url": "https://api.github.com/repos/reactjs/react-magic/events",
  "assignees_url": "https://api.github.com/repos/reactjs/react-magic/assignees{/user}",
  "branches_url": "https://api.github.com/repos/reactjs/react-magic/branches{/branch}",
  "tags_url": "https://api.github.com/repos/reactjs/react-magic/tags",
  "blobs_url": "https://api.github.com/repos/reactjs/react-magic/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/reactjs/react-magic/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/reactjs/react-magic/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/reactjs/react-magic/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/reactjs/react-magic/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/reactjs/react-magic/languages",
  "stargazers_url": "https://api.github.com/repos/reactjs/react-magic/stargazers",
  "contributors_url": "https://api.github.com/repos/reactjs/react-magic/contributors",
  "subscribers_url": "https://api.github.com/repos/reactjs/react-magic/subscribers",
  "subscription_url": "https://api.github.com/repos/reactjs/react-magic/subscription",
  "commits_url": "https://api.github.com/repos/reactjs/react-magic/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/reactjs/react-magic/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/reactjs/react-magic/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/reactjs/react-magic/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/reactjs/react-magic/contents/{+path}",
  "compare_url": "https://api.github.com/repos/reactjs/react-magic/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/reactjs/react-magic/merges",
  "archive_url": "https://api.github.com/repos/reactjs/react-magic/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/reactjs/react-magic/downloads",
  "issues_url": "https://api.github.com/repos/reactjs/react-magic/issues{/number}",
  "pulls_url": "https://api.github.com/repos/reactjs/react-magic/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/reactjs/react-magic/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/reactjs/react-magic/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/reactjs/react-magic/labels{/name}",
  "releases_url": "https://api.github.com/repos/reactjs/react-magic/releases{/id}",
  "deployments_url": "https://api.github.com/repos/reactjs/react-magic/deployments",
  "created_at": "2014-01-05T04:29:56Z",
  "updated_at": "2024-06-14T09:38:10Z",
  "pushed_at": "2023-03-30T01:35:50Z",
  "git_url": "git://github.com/reactjs/react-magic.git",
  "ssh_url": "git@github.com:reactjs/react-magic.git",
  "clone_url": "https://github.com/reactjs/react-magic.git",
  "svn_url": "https://github.com/reactjs/react-magic",
  "homepage": null,
  "size": 276,
  "stargazers_count": 942,
  "watchers_count": 942,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": true,
  "has_discussions": false,
  "forks_count": 101,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 35,
  "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [],
  "visibility": "public",
  "forks": 101,
  "open_issues": 35,
  "watchers": 942,
  "default_branch": "master",
  "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
  }
},
{
  "id": 16710350,
  "node_id": "MDEwOlJlcG9zaXRvcnkxNjcxMDM1MA==",
  "name": "react-php-v8js",
  "full_name": "reactjs/react-php-v8js",
  "private": false,
  "owner": {
      "login": "reactjs",
      "id": 6412038,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6412038?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reactjs",
      "html_url": "https://github.com/reactjs",
      "followers_url": "https://api.github.com/users/reactjs/followers",
      "following_url": "https://api.github.com/users/reactjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/reactjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reactjs/subscriptions",
      "organizations_url": "https://api.github.com/users/reactjs/orgs",
      "repos_url": "https://api.github.com/users/reactjs/repos",
      "events_url": "https://api.github.com/users/reactjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reactjs/received_events",
      "type": "Organization",
      "site_admin": false
  },
  "html_url": "https://github.com/reactjs/react-php-v8js",
  "description": "PHP library that renders React components on the server",
  "fork": false,
  "url": "https://api.github.com/repos/reactjs/react-php-v8js",
  "forks_url": "https://api.github.com/repos/reactjs/react-php-v8js/forks",
  "keys_url": "https://api.github.com/repos/reactjs/react-php-v8js/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/reactjs/react-php-v8js/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/reactjs/react-php-v8js/teams",
  "hooks_url": "https://api.github.com/repos/reactjs/react-php-v8js/hooks",
  "issue_events_url": "https://api.github.com/repos/reactjs/react-php-v8js/issues/events{/number}",
  "events_url": "https://api.github.com/repos/reactjs/react-php-v8js/events",
  "assignees_url": "https://api.github.com/repos/reactjs/react-php-v8js/assignees{/user}",
  "branches_url": "https://api.github.com/repos/reactjs/react-php-v8js/branches{/branch}",
  "tags_url": "https://api.github.com/repos/reactjs/react-php-v8js/tags",
  "blobs_url": "https://api.github.com/repos/reactjs/react-php-v8js/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/reactjs/react-php-v8js/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/reactjs/react-php-v8js/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/reactjs/react-php-v8js/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/reactjs/react-php-v8js/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/reactjs/react-php-v8js/languages",
  "stargazers_url": "https://api.github.com/repos/reactjs/react-php-v8js/stargazers",
  "contributors_url": "https://api.github.com/repos/reactjs/react-php-v8js/contributors",
  "subscribers_url": "https://api.github.com/repos/reactjs/react-php-v8js/subscribers",
  "subscription_url": "https://api.github.com/repos/reactjs/react-php-v8js/subscription",
  "commits_url": "https://api.github.com/repos/reactjs/react-php-v8js/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/reactjs/react-php-v8js/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/reactjs/react-php-v8js/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/reactjs/react-php-v8js/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/reactjs/react-php-v8js/contents/{+path}",
  "compare_url": "https://api.github.com/repos/reactjs/react-php-v8js/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/reactjs/react-php-v8js/merges",
  "archive_url": "https://api.github.com/repos/reactjs/react-php-v8js/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/reactjs/react-php-v8js/downloads",
  "issues_url": "https://api.github.com/repos/reactjs/react-php-v8js/issues{/number}",
  "pulls_url": "https://api.github.com/repos/reactjs/react-php-v8js/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/reactjs/react-php-v8js/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/reactjs/react-php-v8js/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/reactjs/react-php-v8js/labels{/name}",
  "releases_url": "https://api.github.com/repos/reactjs/react-php-v8js/releases{/id}",
  "deployments_url": "https://api.github.com/repos/reactjs/react-php-v8js/deployments",
  "created_at": "2014-02-10T21:41:39Z",
  "updated_at": "2024-06-12T09:37:43Z",
  "pushed_at": "2018-08-02T19:34:15Z",
  "git_url": "git://github.com/reactjs/react-php-v8js.git",
  "ssh_url": "git@github.com:reactjs/react-php-v8js.git",
  "clone_url": "https://github.com/reactjs/react-php-v8js.git",
  "svn_url": "https://github.com/reactjs/react-php-v8js",
  "homepage": "",
  "size": 33,
  "stargazers_count": 1327,
  "watchers_count": 1327,
  "language": "PHP",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 127,
  "mirror_url": null,
  "archived": true,
  "disabled": false,
  "open_issues_count": 16,
  "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [],
  "visibility": "public",
  "forks": 127,
  "open_issues": 16,
  "watchers": 1327,
  "default_branch": "master",
  "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
  }
}]